language: python
cache:
    directories:
        $HOME/.cache/pip
sudo: false
addons:
    apt:
        packages:
            - libzmq3-dev
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: pypy
          env: TOXENV=pypy
install:
    - pip install -U setuptools tox
script:
    - tox
branches:
    except:
        - legacy
deploy:
    provider: pypi
    skip_existing: true
    user: windreamer
    password:
        secure: Qo9ucolE2ajQSbgifbqzfDYD5J09FgYEntXpak1ffPUWxJyeR6H2/uChCGqXC3+ZEkTpzc/MHshHQRRymtPZeHn5etnSHzshWu8njBVLr4I7ft2d5dNGJDxfK2j79HPVnib1MoPNC8kiqP05QD+hyMMQNZDFCHwG1D5bnWNhZYI=
    on:
        tags: true
        repo: douban/dpark
